apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gw7zkvkhr-nodejs
  janus-idp.io/tekton: gw7zkvkhr-nodejs
  backstage.io/kubernetes-id: gw7zkvkhr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gw7zkvkhr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
