apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gw7zkvkhr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gw7zkvkhr-nodejs 
  name: gw7zkvkhr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gw7zkvkhr-nodejs 
