apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gw7zkvkhr-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:b547be565d05e5385b080fde28f04f91b05ce5d7@sha256:a8055b56b794a59bc77cf62e8ae67c099ca6ef86d4bc49b9c7c26c25914d7255
          name: container-image
